---
extends: default

ignore:
  - .venv/
  - build/

rules:
  document-start: disable
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    allowed-values: ["true", "false", "on"]
